version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "calc-basic"
        Alias: "PROD"
        CurrentVersion: "3"
        TargetVersion: "5"